server:
  port: 9000

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "gateway" # http://localhost:9000/actuator/gateway/routes
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always  # actuator에서 상세한 정보들을 확인하기 위해 설정

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000 # 밀리초 단위
        response-timeout: 10s # duration 단위
      default-filters: # 모든 라우터에 적용할 필터
      - name: GlobalFilter
        args:
          baseMessage: Spring Cloud Gateway CommonFilter
      routes:
      - id : common-api
        uri: lb://COMMON-API
        predicates: # 라우터 조건, /cmm/**로 시작하는 요청을 해당 라우터로 요청
        - Path=/cmm/**
        filters: # 라우터 필터, RewritePath는 강제로 Path를 다시 작성
        - RewritePath=/cmm/(?<path>.*),/$\{path}

      - id: product-api
        uri: lb://PRODUCT-API
        predicates:
        - Path=/prd/**
        filters:
        - RewritePath=/prd/(?<path>.*),/$\{path}

# eureka
eureka:
  client:
    register-with-eureka: true      # eureka 서비스 등록 여부
    fetch-registry: true            # eureka 클라이언트 활성화
    registryFetchIntervalSeconds: 5 # eureka에게 서비스 정보를 가져오는 주기 
    disable-delta: true             # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.)
    service-url:
      defaultZone: http://localhost:9010/eureka/
