server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123@localhost:9010/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:질
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
      - id : common-api
        uri: lb://COMMON-API # eureka에 등록된 서비스 이름
        predicates: # 라우터 조건, /cmm/**로 시작하는 요청을 해당 라우터로 요청
        - Path=/cmm/**
        filters:
         - name: LoggingFilter
           args:
            baseMessage: ====================================== COMMON-API ======================================
            preLogger: true
            postLogger: true
      - id: product-api
        uri: lb://PRODUCT-API
        predicates:
        - Path=/prd/**
      - id: auth-server
        uri: lb://AUTH-SERVER
        predicates:
        - Path=/auth/**

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "gateway" # http://localhost:9000/actuator/gateway/routes
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always  # actuator에서 상세한 정보들을 확인하기 위해 설정

