server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123@localhost:9010/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id : common-api
        uri: lb://COMMON-API # eureka에 등록된 서비스 이름
        predicates: # 라우터 조건, /cmm/**로 시작하는 요청을 해당 라우터로 요청
        - Path=/cmm/**
      - id: product-api
        uri: lb://PRODUCT-API
        predicates:
        - Path=/prd/**

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "gateway" # http://localhost:9000/actuator/gateway/routes
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always  # actuator에서 상세한 정보들을 확인하기 위해 설정

