server:
  port: 9010

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin123

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9010/eureka/